#!/bin/sh

if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  mount -o remount,rw /
  if [ $? -ne 0 ]; then
  	echo "Error remounting root partition read-write."
  	echo "Reboot device then try installing again."
  	exit 1
  fi
fi

/bin/rm -f /usr/lib/luna/java/FileMgr.jar

/bin/rm -f /usr/share/dbus-1/system-services/ca.canucksoftware.filemgr.service

/bin/rm -f /etc/event.d/ca.canucksoftware.filemgr

if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  mount -o remount,ro /
  killall -9 java
fi

exit 0
