#!/bin/sh

ID=ca.canucksoftware.filemgr

#remount root using technique that won't cause the random remounting error
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
	/usr/sbin/rootfs_open -w
fi

#remove java service files if they exist
/bin/rm -f /usr/lib/luna/java/FileMgr.jar
/bin/rm -f /usr/share/dbus-1/system-services/$ID.service
/bin/rm -f /etc/event.d/$ID

#remove dbus service file
/bin/rm -f /var/palm/ls2/services/prv/$ID.service
/bin/rm -f /var/palm/ls2/services/pub/$ID.service

exit 0
